# Subordination

**Complement clauses** are introduced by the particle *nai*. All complement clauses are finite (they always have a finite verb).

:::: ex
::: gl
| - Kabasiesu nai korashiego.
| kabas-ie-su   nai korash-ie-go
| know-PST-3plm SUB be.happy-PST-1s
| 'They knew I was/have been happy.'
:::
::::

:::: ex
::: gl
| - Tokago nai noirgah-a-go nil.
| tok-a-go    nai sibu-a-go   ni-l
| want-PRS-1s SUB meet-PRS-1s 2s-ACC:SG
| 'I want to meet you.'
:::
::::

Subject complement clauses are preceded by an independent clause of the form 'be.PRED + ADJ/PTCP'.

:::: ex
::: gl
| - Omalah pushaitam nai sibuemin.
| om-a-lah        pushait-am  nai sibu-o-min
| be.PRED-PRS-3sn scare-PTCP  SUB meet-PST-1pl
| 'It scares me that we will meet.'
:::
::::

**Adverbial clauses** are introduced by a variety of adverbial subordinating conjunctions.

**Relative clauses** are introduced by *ki* and a resumptive pronoun is used. The resumptive pronoun in the relative clause is in the case and position it would be if the clause were independent. A nominative resumptive pronoun is generally omitted. If the antecedent is the object of the main clause and the subject of the relative clause, *ki* and the subject pronoun are omitted and the antecedent is in the nominative case.

:::: ex
::: gl
| - Lonum ki voinalo korashalo.
| lonu-m  ki  voin-a-lo     korash-a-lo
| boy-PL  REL play-PRS-3sm  be.happy-PRS-3sm
| 'The boy who plays is happy.'
:::
::::

:::: ex
::: gl
| - Nem korashielo mol noirgahielo lonu voinielo.
| nem       korash-ie-lo    mol   noirgah-ie-lo lonu    voin-ie-lo
| yesterday be.happy-PST-3sm GRND  see-PST-3sm   boy.NOM play-PST-3sm
| 'Yesterday he rejoiced in seeing the boy who was playing.'
:::
::::

Cf. with the object complement clause *Nem korashielo mol noirgahielo nai lonu voinielo* 'Yesterday he rejoiced in seeing that the boy was playing.'

:::: ex
::: gl
| - Firkiniego catieru ki noirgahieni laholu.
| firkin-ie-go  catie-ru        ki  noirgah-ie-ni lah-olu
| speak-PST-1s  person-INST:SG  REL see-PST-2s    3sn-ACC:SG
| 'I spoke with the person you saw.'
:::
::::

:::: ex
::: gl
| - Noirgahiego catiel ki firkinieni lahur.
| noirgah-ie-go catie-l       ki  firkin-ie-ni  lah-ur
| see-PST-1s    person-ACC:SG REL speak-PST-2s  3sn-INST:SG
| 'I saw the person you spoke to.'
:::
::::