# Verbs

*Revision*: Verbs end in vowel (are there C-final verbs? what about nouns?). In the Present, the vowel coalesces with the Present Tense suffix *-u*: a-u > o, e-u > ie, i-u > y, o-u > o, u-u > u. Past and Future are analytic? Past uses *lusho* 'to go' as auxiliary (new 'to go' is different). Future is just the verb stem plus the Subj suffixes.

Infinitive: -sh (< -tʲ). Hypothetical from -bʷi, a form of future?

Passive: it was -s, now it has Non-Past form (Present and Future) which is original Gnomic (that takes on future meaning in Active). Passive Past is with auxiliary *dlanti* 'to come'.

*reika* 'to turn'

| Active | present   | past           | future    | hypothetical      |
|--------|-----------|----------------|-----------|-------------------|
| 1s     | reiko-go  | lurgo  reika-s | reika-go  | lurby-go  reika-s |
| 2s     | reiko-ni  | lurni  reika-s | reika-ni  | lurby-ni  reika-s |
| 3sm    | reiko-lo  | luelo  reika-s | reika-lo  | lurby-lo  reika-s |
| 3sf    | reiko-re  | luere  reika-s | reika-re  | lurby-re  reika-s |
| 3sn    | reiko-lah | luelah reika-s | reika-lah | lurby-lah reika-s |
| 1pl    | reiko-min | lurmin reika-s | reika-min | lurby-min reika-s |
| 2pl    | reiko-ty  | lusty  reika-s | reika-ty  | lurby-ty  reika-s |
| 3plm   | reiko-su  | luesu  reika-s | reika-su  | lurby-su  reika-s |
| 3plf   | reiko-shi | lueshi reika-s | reika-shi | lurby-shi reika-s |
| 3pln   | reiko-sah | luesah reika-s | reika-sah | lurby-sah reika-s |

| Passive | non-past   | past          |
|---------|------------|---------------|
| 1s      | reika-gos  | lango reika-s |
| 2s      | reika-nis  | leni  reika-s |
| 3sm     | reika-los  | lelo  reika-s |
| 3sf     | reika-res  | lere  reika-s |
| 3sn     | reika-les  | lelah reika-s |
| 1pl     | reika-meis | lemin reika-s |
| 2pl     | reika-tys  | lanty reika-s |
| 3plm    | reika-sus  | lesu  reika-s |
| 3plf    | reika-shis | leshi reika-s |
| 3pln    | reika-ses  | lesah reika-s |

\ex \begingl \glpreamble Lango (done)ganis nide.//
\gla lan-go       (done)gani-s     ni-de//
\glb PST:PASS-1sg save-PASS.PRT  2s-ABL:SG//
\glft `I was saved by you.'//
\endgl \xe

Present participles are formed with the suffix -*m* which is attached to the verb root and they can be declined according the to consonant declination.

\ex \begingl \glpreamble Catieni shonamen//
\gla catie-ni      shona-m-en//
\glb person-GEN:SG think-PTCP-GEN:SG//
\glft `Of the thinking person.'//
\endgl \xe

## Copula

There are two copulas in Kalahim, *om-* (< *aumi-*) and *ash-* (< *ashi-*). The first is used with the Predicative case and refers to a permanent or substantial feature of the subject. For example, *omy ned-es* 'I am (a) man'. *ash-* is used with temporary states and feelings, like in *ashe cul* 'it is sweet'.

| aum- | present | past        | future    | hypothetical |
|------|---------|-------------|-----------|--------------|
| 1s   | omy     | on-go/ue-go | om-ei-go  | om-by-go     |
| 2s   | omy-ni  | ue-ni       | om-ei-ni  | om-by-ni     |
| 3sm  | omy     | ue-lo       | om-ei-lo  | om-by-lo     |
| 3sf  | omy     | ue-re       | om-ei-re  | om-by-re     |
| 3sn  | omy     | ue-lah      | om-ei-lah | om-by-lah    |
| 1pl  | omy-min | ue-min      | om-ei-min | om-by-min    |
| 2pl  | omy-ty  | on-ty/ue-ty | om-ei-ty  | om-by-ty     |
| 3plm | omy-su  | ue-su       | om-ei-su  | om-by-su     |
| 3plf | omy-shi | ue-shi      | om-ei-shi | om-by-shi    |
| 3pln | omy-sah | ue-sah      | om-ei-sah | om-by-sah    |

Present should have stem in -ie but it is reduced to -e because of preceding -sh (only when unstressed).

| ash- | present   | past    | future    | hypothetical |
|------|-----------|---------|-----------|--------------|
| 1s   | ashe      | e-go    | ash-o-go  | e-by-go      |
| 2s   | ashie-ni  | e-ni    | ash-o-ni  | e-by-ni      |
| 3sm  | ashe      | ash-lo  | ash-o-lo  | e-by-lo      |
| 3sf  | ashe      | e-re    | ash-o-re  | e-by-re      |
| 3sn  | ashe      | ash-lah | ash-o-lah | e-by-lah     |
| 1pl  | ashie-min | e-min   | ash-o-min | e-by-min     |
| 2pl  | ashie-ty  | ash-ty  | ash-o-ty  | e-by-ty      |
| 3plm | ashie-su  | e-shu   | ash-o-su  | e-by-su      |
| 3plf | ashie-shi | e-shi   | ash-o-shi | e-by-shi     |
| 3pln | ashie-sah | e-shah  | ash-o-sah | e-by-sah     |

## Locative *om-*

The verb *om-*, which means 'to be in some place' derives from *aum-*, although its paradigm has regularised and follows the default verbal conjugation. In the 3rd Neuter Singular and Plural it is also used together with the Predicative case as an expletive to mean 'There is/are'.

\ex \begingl \glpreamble Omogo Limlin'ija.//
\gla omo-go         Limlin'-ija//
\glb be.LOC.PRS-1s  Limlin-LOC:SG//
\glft `I am in Limlin.'//
\endgl \xe

\ex \begingl \glpreamble Luesah omis jekines.//
\gla luesah omi-s jeki-nes//
\glb PST.3pl.N be.EXPL-PST.PRTC monkey-PRED:PL//
\glft `There were (some) monkeys.'//
\endgl \xe

## Negation

A verb is negated by placing the negative adverb *an* after the verb.

\ex \begingl \glpreamble Dlantigo an fladriba.//
\gla dlanti-go an fladri-ba//
\glb come.FUT-1s NEG forest-ALL:SG//
\glft `I will not come to the forest.'//
\endgl \xe